URLS = {
    "login": {  # 登录接口
        "req_url": "https://js.lgb360.com/lgb/user/loginByPassword.do",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "token": "",
            "memberId": "",
            "mobileTerminal": "0",
            "appversion": "3.0.6",
            "User-Agent": "LGB/3.0.6 (HMA-AL00; Android 10; zh_CN_#Hans; e4802ed3-c836-4ba8-822c-51dc9cdac4f8; 3626613241)",
            "Content-Type": "application/x-www-form-urlencoded",
            "Host": "js.lgb360.com",
            "Connection": "Keep-Alive",
            "Accept-Encoding": "gzip"
        },
    },
    "start": {  # 开始答题接口
        "req_url": "https://aqy-app.lgb360.com/aqy/ques/startCompetition",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
        },
    },
    "answer": {  # 回答问题接口
        "req_url": "https://aqy-app.lgb360.com/aqy/ques/answerQues",
        "req_type": "post",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "competition": {  # 查询接口
        "req_url": "https://aqy-app.lgb360.com/aqy/regist/competition",
        "req_type": "get",
        "re_try": 10,
        "re_time": 3,
        "s_time": 0.1,
        "is_json": True,
        "header": {
            "Host": "aqy-app.lgb360.com",
            "accept": "application/json, text/plain, */*",
            "token": "",
            "User-Agent": "",
            "memberId": "",
            "content-type": "application/json;charset=UTF-8",
            "origin": "https://aqy-app.lgb360.com",
            "x-requested-with": "com.hxak.liangongbao",
            "sec-fetch-site": "same-origin",
            "sec-fetch-mode": "cors",
            "sec-fetch-dest": "empty",
            "accept-encoding": "gzip, deflate",
            "accept-language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
        },
    },
    "web_login": {
        "req_url": "https://aqy.lgb360.com/#/login",
        "re_try": 10,
    },
    "web_home": {
        "req_url": "https://aqy.lgb360.com/#/",
        "re_try": 10,
    },
    "web_answer": {
        "req_url": "https://aqy.lgb360.com/#/answer",
    }
}
